name: my_mail
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  http: ^0.13.5
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  jwt_decoder: ^2.0.1
  intl: ^0.17.0
  get_storage: ^2.0.3
  flutter_spinkit: ^5.1.0
  lottie: ^1.4.2
  animated_text_kit: ^4.2.2

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Muktadir
      fonts:
        - asset: fonts/Product_Sans_Bold.ttf
        - asset: fonts/Product_Sans_Regular.ttf

